<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "abbreviations"
 *
 * Auto generated by Extension Builder 2014-05-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Abbreviations',
	'description' => 'Abbreviations for Typo3.',
	'category' => 'be',
	'author' => 'Ben Walch',
	'author_email' => 'ben.walch@world-direct.at',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);